// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
)

var _ = (*headerMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (auraHeader AuraHeader) MarshalJSON() ([]byte, error) {
	type AuraHeader struct {
		ParentHash  common.Hash    `json:"parentHash"       gencodec:"required"`
		UncleHash   common.Hash    `json:"sha3Uncles"       gencodec:"required"`
		Coinbase    common.Address `json:"miner"            gencodec:"required"`
		Root        common.Hash    `json:"stateRoot"        gencodec:"required"`
		TxHash      common.Hash    `json:"transactionsRoot" gencodec:"required"`
		ReceiptHash common.Hash    `json:"receiptsRoot"     gencodec:"required"`
		Bloom       Bloom          `json:"logsBloom"        gencodec:"required"`
		Difficulty  *hexutil.Big   `json:"difficulty"       gencodec:"required"`
		Number      *hexutil.Big   `json:"number"           gencodec:"required"`
		GasLimit    hexutil.Uint64 `json:"gasLimit"         gencodec:"required"`
		GasUsed     hexutil.Uint64 `json:"gasUsed"          gencodec:"required"`
		Time        hexutil.Uint64 `json:"timestamp"        gencodec:"required"`
		Extra       hexutil.Bytes  `json:"extraData"        gencodec:"required"`
		Seal        [][]byte       `json:"sealFields"       gencodec:"required"       rlp:"tail"`
		Hash        common.Hash    `json:"hash"`
	}
	var enc AuraHeader
	enc.ParentHash = auraHeader.ParentHash
	enc.UncleHash = auraHeader.UncleHash
	enc.Coinbase = auraHeader.Coinbase
	enc.Root = auraHeader.Root
	enc.TxHash = auraHeader.TxHash
	enc.ReceiptHash = auraHeader.ReceiptHash
	enc.Bloom = auraHeader.Bloom
	enc.Difficulty = (*hexutil.Big)(auraHeader.Difficulty)
	enc.Number = (*hexutil.Big)(auraHeader.Number)
	enc.GasLimit = hexutil.Uint64(auraHeader.GasLimit)
	enc.GasUsed = hexutil.Uint64(auraHeader.GasUsed)
	enc.Time = hexutil.Uint64(auraHeader.Time)
	enc.Extra = auraHeader.Extra
	enc.Seal = auraHeader.Seal
	enc.Hash = auraHeader.Hash()
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (auraHeader *AuraHeader) UnmarshalJSON(input []byte) error {
	type AuraHeader struct {
		ParentHash  *common.Hash    `json:"parentHash"       gencodec:"required"`
		UncleHash   *common.Hash    `json:"sha3Uncles"       gencodec:"required"`
		Coinbase    *common.Address `json:"miner"            gencodec:"required"`
		Root        *common.Hash    `json:"stateRoot"        gencodec:"required"`
		TxHash      *common.Hash    `json:"transactionsRoot" gencodec:"required"`
		ReceiptHash *common.Hash    `json:"receiptsRoot"     gencodec:"required"`
		Bloom       *Bloom          `json:"logsBloom"        gencodec:"required"`
		Difficulty  *hexutil.Big    `json:"difficulty"       gencodec:"required"`
		Number      *hexutil.Big    `json:"number"           gencodec:"required"`
		GasLimit    *hexutil.Uint64 `json:"gasLimit"         gencodec:"required"`
		GasUsed     *hexutil.Uint64 `json:"gasUsed"          gencodec:"required"`
		Time        *hexutil.Uint64 `json:"timestamp"        gencodec:"required"`
		Extra       *hexutil.Bytes  `json:"extraData"        gencodec:"required"`
		Seal        [][]byte        `json:"sealFields"       gencodec:"required"       rlp:"tail"`
	}
	var dec AuraHeader
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.ParentHash == nil {
		return errors.New("missing required field 'parentHash' for AuraHeader")
	}
	auraHeader.ParentHash = *dec.ParentHash
	if dec.UncleHash == nil {
		return errors.New("missing required field 'sha3Uncles' for AuraHeader")
	}
	auraHeader.UncleHash = *dec.UncleHash
	if dec.Coinbase == nil {
		return errors.New("missing required field 'miner' for AuraHeader")
	}
	auraHeader.Coinbase = *dec.Coinbase
	if dec.Root == nil {
		return errors.New("missing required field 'stateRoot' for AuraHeader")
	}
	auraHeader.Root = *dec.Root
	if dec.TxHash == nil {
		return errors.New("missing required field 'transactionsRoot' for AuraHeader")
	}
	auraHeader.TxHash = *dec.TxHash
	if dec.ReceiptHash == nil {
		return errors.New("missing required field 'receiptsRoot' for AuraHeader")
	}
	auraHeader.ReceiptHash = *dec.ReceiptHash
	if dec.Bloom == nil {
		return errors.New("missing required field 'logsBloom' for AuraHeader")
	}
	auraHeader.Bloom = *dec.Bloom
	if dec.Difficulty == nil {
		return errors.New("missing required field 'difficulty' for AuraHeader")
	}
	auraHeader.Difficulty = (*big.Int)(dec.Difficulty)
	if dec.Number == nil {
		return errors.New("missing required field 'number' for AuraHeader")
	}
	auraHeader.Number = (*big.Int)(dec.Number)
	if dec.GasLimit == nil {
		return errors.New("missing required field 'gasLimit' for AuraHeader")
	}
	auraHeader.GasLimit = uint64(*dec.GasLimit)
	if dec.GasUsed == nil {
		return errors.New("missing required field 'gasUsed' for AuraHeader")
	}
	auraHeader.GasUsed = uint64(*dec.GasUsed)
	if dec.Time == nil {
		return errors.New("missing required field 'timestamp' for AuraHeader")
	}
	auraHeader.Time = uint64(*dec.Time)
	if dec.Extra == nil {
		return errors.New("missing required field 'extraData' for AuraHeader")
	}
	auraHeader.Extra = *dec.Extra
	if dec.Seal == nil {
		return errors.New("missing required field 'sealFields' for AuraHeader")
	}
	auraHeader.Seal = dec.Seal
	return nil
}
