name: Test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.16 ]
        platform: [ ubuntu-18.04 ]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          go get -v -t -d ./...

      - name: Lint
        run: go run ./build/pan_ci.go lint

      - name: Test
        run: SKIP_ANDROID=true SKIP_FACEBOOK_TEST=true SKIP_GOLANG_BINDINGS_TEST=true go run ./build/pan_ci.go test